### PR TITLE
pointer-events: none, for hints

### PR DESCRIPTION
**Pull request by AleshaOleg**

### CODE REVIEW

**Comment by slmgc** [comment]
Hi! Could you tell me, what's the reasoning behind disabling pointer events for tooltips?

**Comment by AleshaOleg** [comment]
Hey. The reason is, to make clickable other buttons when an actual hint is hiding with animation.
I take a look to demo, and if I quickly try to click sibling button, it's not clicked, because hint I cover this button.

**Comment by AleshaOleg** [comment]
It's more like a proposal and not a recommendation. Really, I didn't know, it's right or wrong from UX part

**Comment by slmgc** [comment]
Did you check the online demo or the source code demo? The online demo is outdated and is based on the v1 react-hint version which doesn't hide the hint on hover by default. This was changed in v2 and there is a setting for the use-cases when it's needed.

I don't think it's a good idea to disable all pointer events in tooltips by default as it will prevent using interactive content (buttons, inputs, links, drop-downs, etc.) inside of the tooltip.

**Comment by ambz24** [comment]
Get Outlook for iOS<https://aka.ms/o0ukef>
_____________________________

**Comment by AleshaOleg** [comment]
I checked a source demo, where 5-7 buttons located in a row.
But, it will be disabled only, for a tip, and not for elements inside it.

OK, anyway can be closed now

**Comment by ambz24** [comment]
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by slmgc** [comment]
Added a screenshot for a reference:
screen shot 2017-08-28 at 21 10 40
In case you add `pointer-events: none`, the button `123` inside of the tooltip becomes unclickable.

**Pull request closed without merging**
